[sinks.parseable]
type = "http"
inputs = [ "zerolog_test" ]
compression = "none"
method = "post"
auth.strategy = "basic"
auth.password = "admin"
auth.user = "admin"
encoding.codec = "json"
uri = "http://localhost:8000/api/v1/logstream/demo"
